name: way_to_doctor_doctor
description: A new Flutter project.

publish_to: 'none' 

version: 1.4.4+41

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  shared_preferences: ^2.2.0
  flutter_overlay_loader: ^2.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  animate_do: ^3.0.2
  carousel_slider: ^4.2.1
  http: ^1.1.0
  fluttertoast: ^8.2.2
  # flutter_zoom_drawer: ^3.0.3
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
  image_picker: ^1.0.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^15.0.1
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  firebase_ui_firestore: ^1.5.4
  syncfusion_flutter_pdfviewer: ^22.1.37
  agora_rtc_engine: ^6.2.1
  stop_watch_timer:
  loading_animation_widget: ^1.2.0+4
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0
  file_picker: ^5.3.2
  permission_handler: ^10.4.1
  # record: ^4.4.3
  # audioplayers: 
  #slide_to_act: ^2.0.1
  slide_action: ^0.0.2
  flutter_styled_toast: ^2.1.3
  svg_drawing_animation: ^0.11.0
  infinite_scroll_pagination: ^3.2.0
  connectivity_plus: ^4.0.1
  persistent_bottom_nav_bar: ^5.0.2
  path: ^1.8.3
  calendar_appbar: ^0.0.6
  calendar_agenda: ^0.0.2+3
  url_launcher: ^6.1.11
  mask_text_input_formatter: ^2.4.0
  google_api_headers: ^2.0.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.3.1
  geocoding: ^2.1.0
  google_maps_webservice: ^0.0.19
  flutter_google_places: ^0.3.0
  uuid: ^3.0.7
  voice_message_package: ^1.0.41
  lottie: ^2.4.0
  flutter_zoom_drawer: ^3.1.1
  ntp: ^2.0.0
  flutter_sound: ^9.2.13
  firebase_auth: ^4.6.3
  expandable_page_view: ^1.0.17
  webview_flutter: ^4.2.2
  crypto: ^3.0.3
  quiver: ^3.2.1
  eraser: ^2.0.1



dependency_overrides:
  intl: ^0.17.0
  http: ^0.13.1
  google_api_headers: ^1.0.0
  flutter_svg: ^1.1.6
  syncfusion_flutter_core: ^22.1.37
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true

flutter_native_splash:  
  background_image: assets/images/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/